// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMkAsZqzdYk0ykoXtmqGVkDq576OwvUc4',
    appId: '1:219244400700:web:44c41a74479df33ae03339',
    messagingSenderId: '219244400700',
    projectId: 'hust-cv-202416491',
    authDomain: 'hust-cv-202416491.firebaseapp.com',
    storageBucket: 'hust-cv-202416491.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsxmz-A7NGE7RxQZxaoOuPiWhIQozOHwA',
    appId: '1:219244400700:android:b3a2dbaf63978635e03339',
    messagingSenderId: '219244400700',
    projectId: 'hust-cv-202416491',
    storageBucket: 'hust-cv-202416491.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm1hiJXZZMvFPuBflBOT7Gd24Mou31NVQ',
    appId: '1:219244400700:ios:44292fcdaaa5e14ee03339',
    messagingSenderId: '219244400700',
    projectId: 'hust-cv-202416491',
    storageBucket: 'hust-cv-202416491.appspot.com',
    iosBundleId: 'com.example.choreappFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm1hiJXZZMvFPuBflBOT7Gd24Mou31NVQ',
    appId: '1:219244400700:ios:44292fcdaaa5e14ee03339',
    messagingSenderId: '219244400700',
    projectId: 'hust-cv-202416491',
    storageBucket: 'hust-cv-202416491.appspot.com',
    iosBundleId: 'com.example.choreappFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMkAsZqzdYk0ykoXtmqGVkDq576OwvUc4',
    appId: '1:219244400700:web:2f54d4a8fbfa3695e03339',
    messagingSenderId: '219244400700',
    projectId: 'hust-cv-202416491',
    authDomain: 'hust-cv-202416491.firebaseapp.com',
    storageBucket: 'hust-cv-202416491.appspot.com',
  );
}
