version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: beafort
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Username=myuser;Password=mypassword;Database=mydatabase;"
    depends_on:
      - postgres