GET http://localhost:5270/chores/
Authorization: Bearer CfDJ8Llo-NNeQwpHvD97MZvaD7x3hW50ZFHXw6WOTsJKMSNC5Hn43wBMMYYzuB4G9MbEN-jEkV0efZXvrPb-n0ChXGIq-ql-on_UJ7f2u-8tSZRygaxe9FEPjV3sDXAYVSeeOgyzeC0wYtEJRjKfA2p5egJsiJtFV8Yu0uu8Snl2rzb-j2rS6uyS3PSyxz3b-Udq5JyJShjdsq59Jc_tWwm8YCXK5KPaoVRHvjst79ZRU8gw396qk0H-n3V3P3ZKZzQGoZIwci7tjsTT_Ysai4TDIWfPWKIRswF8RFI-W04tfUxz6vahflk2Cw6Bbq01JT6PLfC4k3CCgSl9WHpUPamVEIjuVp5Ijx3UDLNlOKMPKTRgr3ol1HXYs4mOGHPkCDUnplScjd2pOXz9mklgGCv37oA1Alb1_Cd8LiWFN6eCR5cUZjGd8T7MS_Kkj6H5fpyPxnIEU5WI2BWDtDwahu0_K-km29PUkoUaXtfHUM42cnHAqFVmFfQ8qAJnWTGq5bZH8WwunV0CL4vjh5-N0GjHqua1_eSBY--wIU9m8JtjJ629qA5tvaPG0xJww6-IuEBKEGItoIXpxR-JcgXFmLPPt1MhA9GvsK-rSdI4eGh6Ey1sbtcxSeHP0k19r-kDPre7WSi4jcKN_xBgxvp96xZGpYYcBnZtf-0oLbHIt9cUi4wwQu5mW95xGefTsx1bUHAXrlrTnF6845xgWeSIJMcRCn4
###
POST http://localhost:5270/chores
Content-Type: application/json

{
    "Name": "Test3",
    "Deadline": "2024-09-10T17:26:22+07:00"
}
###
DELETE http://localhost:5270/chores/1
###
PUT http://localhost:5270/chores/2
Content-Type: application/json

{
    "Name": "Null",
    "deadline": "2024-09-09T17:26:22"
}
###
POST http://localhost:5270/register
Content-Type: application/json

{
    "email": "beafortgm@gmail.com",
    "password": "Hieukdmcqn1!"
}
###
POST http://localhost:5270/user/register
Content-Type: application/json

{
    "email": "beafortworkm@gmail.com",
    "password": "Hieukdmcqn1!",
    "name": "Hieu"
}
###
POST http://localhost:5270/login
Content-Type: application/json

{
    "email": "beafortgm@gmail.com",
    "password": "Hieukdmcqn1!"
}
###
GET http://localhost:5270/user/f3a43e85-ba4f-4b22-9f38-657e8a6eff24
Authorization: Bearer CfDJ8Llo-NNeQwpHvD97MZvaD7wrW1ipdRQzNvNd4pn2f5weSk8bciuU8EiOVPa3L3jcR749oFiFBHiBphgL9mQhwse-rMDVCYcbyqBKDlKiuvPpRp0rVsr_k4kKYSzd4ECawfdSxe47JPFHbIxcHXojS5Q5dSpArBpsqeM8TzavU4AfQXfT4U2Wl664Loig6YMN7jWnGmJ6spKftohiWXo9cswii89ORTeOIuhDGssiFyUh1WhoxFoed-wZjIUqBrty-iiFT5wBzhcBg31ac1jl2ZPUPnNnjTwUPnPIOSxw27vjzGNk-NA856cuxK_b4YpGzAav8svARJ7B9xIqvox8fkChLEtE8t-opxIVqBhgY3_Wcikgpvpba0aKavRqC6qa3-zFYn4b2o2ePy9F-fkyn768S5_DTXGiwvS5llBji_WqLtmzwa_9_QevjZZPB8uwm_HulCSPrrH6CG_JJEFfogUWOzRNR1GEg1ksE5OH23ZLk3f_WhMOE4Sjj9-qlW9hwYmWB_FGC2rln7rO5-kH3FEcD-YEjwQIievNR_VhBFBD2ZMtU6qSTrTOD9xTANLyJTFTJbVT7z33KHkm5Og1FseQPctbMM118x-5J9LdTuQfw97s_VoZ-wVVniwuD4bFn_0s8ysDZGvM-zWX4SK0AWnYLD5zb6eYy74YSjM5SzvGy7eXnOL6SgFzXzeA7y_fda25qq_kwvkNojIwedGLKJQ
###
DELETE http://localhost:5270/user/38ccdbc1-467c-4491-8c90-bdd1006e17d5
Authorization:  Bearer CfDJ8Llo-NNeQwpHvD97MZvaD7ybqcvi2znDSevbEmNpBx4atKw73B-4q9l1bUE9JW3WkwTPdfgzb3voE--HvzCKdlDC98T3uP66oYFn3mM3kTVWitwOygFyDArTM4jFw3bYGdzk7AWJygU04gizQz-aqs7ODD6yAWwORjcT8awNFtb0DlNqBM9POfSeTWbYzYXo3XE_pedRZwn9qVrMbp0TfMhEzSJw6L5IqebJRW-0o1r3cIWg3hebeLxPKfxJw21Vtxclrxnp0BwKT21d2WCcwS7gfgqsyIqMB9kaEIGvdEBNxwXXbnjbs86BnyJyOGqxMBNznugiACa4Rq77cBa0AuClC9-yE0yg3iDvmTrrV_dd6M3ebTeAAtr-n7uTlwTpTNx3eyphY-1Lv_NY7MvGAhawqODKjWE_2wsQvWOYcnrHgaFnW4cDd4X2iZgkEW_L1Xqh6vwqJ3N0j0P7P0B5JIkasUwC__cpxmRWZQR5hEALptKiCBuhm8C8JOXFl-yZFH7d8vMBduRU-oI7gX-7_V62azEpAjaC3aiV3tEyI6E9KzZNU8kN2pKjmKfbg_9OmxAsvEXQ6eG5V4I8AANB7f2fl_Zt8w0F0pv7DwsjNc7Dry19zxrE7vd05_anrPfkKTukaumLtEVdAE9WOSwE99kDQTyWVg0rvM987jjbXhOyoJ0W_ZCXrOWYV4fBqnZPna35HdL_cLM43RtDSrxTaWQ
###
PUT  http://localhost:5270/user/f3a43e85-ba4f-4b22-9f38-657e8a6eff24/chores
Authorization: Bearer CfDJ8Llo-NNeQwpHvD97MZvaD7wrW1ipdRQzNvNd4pn2f5weSk8bciuU8EiOVPa3L3jcR749oFiFBHiBphgL9mQhwse-rMDVCYcbyqBKDlKiuvPpRp0rVsr_k4kKYSzd4ECawfdSxe47JPFHbIxcHXojS5Q5dSpArBpsqeM8TzavU4AfQXfT4U2Wl664Loig6YMN7jWnGmJ6spKftohiWXo9cswii89ORTeOIuhDGssiFyUh1WhoxFoed-wZjIUqBrty-iiFT5wBzhcBg31ac1jl2ZPUPnNnjTwUPnPIOSxw27vjzGNk-NA856cuxK_b4YpGzAav8svARJ7B9xIqvox8fkChLEtE8t-opxIVqBhgY3_Wcikgpvpba0aKavRqC6qa3-zFYn4b2o2ePy9F-fkyn768S5_DTXGiwvS5llBji_WqLtmzwa_9_QevjZZPB8uwm_HulCSPrrH6CG_JJEFfogUWOzRNR1GEg1ksE5OH23ZLk3f_WhMOE4Sjj9-qlW9hwYmWB_FGC2rln7rO5-kH3FEcD-YEjwQIievNR_VhBFBD2ZMtU6qSTrTOD9xTANLyJTFTJbVT7z33KHkm5Og1FseQPctbMM118x-5J9LdTuQfw97s_VoZ-wVVniwuD4bFn_0s8ysDZGvM-zWX4SK0AWnYLD5zb6eYy74YSjM5SzvGy7eXnOL6SgFzXzeA7y_fda25qq_kwvkNojIwedGLKJQ
Content-Type: application/json

{
    "choreIds": [7, 8, 9, 10]
}
###
POST http://localhost:5270/refresh
Content-Type: application/json

{
    "refreshToken" : "CfDJ8HzTZ3NU6dpKt_z5BcMhzxEsbmG6bYNjr4cZzssR5HaCcZvbkWsk8G2VG_eWWdq7w9DPj-cz_3XNYSE982MC298R2NzfGY91ji2WLBjCaAmVmgWic7LDvNsNAAZPylTH5sDksxrrnVVBBxMHnZjuEDT6Ok9hqRZ436uE8B2-x9PJuukLZJp0Acq0SGYfkGgBH_TL6UhBwqH3QW11TvHgIQWCuZzXxCpCmpo5iTQVsLJD_tJ_Yu_5RDera0mostXHOupAXgyRaOExf5txA-a2WSqwcyq1K6ckpZLlMs8CxsbhdQbdi9NeCnXQH0aHZdCmWUoPzgw5Ofccdc-TD2uWdEF8vBI6yVvtPHcYvSC0j4Ohe2hQJENa4dKsWP2hOBpTvcrngUxU3XtidvKnZjOGO-AcS5O3ye7sxGXdeglkdYffnAFW2IpNUdla-HQpjl5bQLkvh4xtuR4uaYdQuusE9Hm6-ibPh9TOFdg_GD-PyY7s4OXNKz5ZIeb0aeiLgvwOaXk2v5KXE4JT6AkTBuuas7kAiJlP4jJcjG6wY399tz3xXRP6JUyUdpdbL9fmyfuErmFd0M0j76oRrSpVKCk0nIZQcO_OByp2Tf1NwajAt9Izof2T-NRDRVPMrF67O4cMtT1yeZuLM8qorvbD36xvSiP2rcVFQ9rPzQNwhiSQC6B1T5VgrZ6qKgFAV2VWxDJKdy_PkSi-9A0zhyvYgnQg77k"
    
}
###
POST http://localhost:5270/user/logout
Authorization: Bearer CfDJ8HzTZ3NU6dpKt_z5BcMhzxE9KTvTVp9nFou6_5fwYM42m1ROUndgxk__bDNwZca7F9Lydce-7yoOlHVOqFGX8D6kKmTriYjmGjrqnYtL-0RYToCoerja61oCknZq604D8ka15eZgSKJPvDpVLVw2lJLA1AyF4Bh4QJh4Cqijx-EKWDVxD5XXnt8zqX8NgraKbzq4qvvVpUZvBBpNNmAF3cMoFHWTIoKqamb34yWwOfpBUYpMRJuiHOMOH2CBNnZo2HTXnEwPzrlhyOvDPgmuMT93G9KscH6YZar6VocrBUsLjfiI5nT2mmbq_2pGveem2C9Fba2lBAoSA7QBnQcnknP87QP7hNbMM3zIlMchMkVj1wIMSA1Ruh5aklGPxQWxSO1riz3tZWQjJkI2aMMCe0WiTEK5Q8l0HfXiFfMlqW1xYy5aBHgqBfQRaIAAeuGHzdFjMsQ-XLhkuiXXVXqnhlQyriGa4z1bpG9-bUR2XUmjTiuFc9Drr5YofT_ddFQS5r_6lH49MQ8XYK5V7gBNLTizuIsOc7RZ2WqAwUxnHwBycw8JwcbvUxNv2kMCaMcQllGHKd-6LneaXpHVlXwW4XNiFiuELklRTlxYvrsPtJexyXZ-ALcdzoxqmE_CcgmSbcsVPQ9q6esiOcs1HybXf1vZ0rVPObWDwoX8U6mTtpvkisWPIMdO-c7mCLIglEN6o9kzgfl8yTBayyZZv-mbsmg
Content-Type: application/json

{}
###
GET http://localhost:5270/user/info
Authorization: Bearer CfDJ8HzTZ3NU6dpKt_z5BcMhzxFD6Hk3KTllBIrsvZv80mCYhqONYkfw9fTsRnyCPdjfMN-rvzGfKPruDHMtloOUpwcsNALmxRnU5OdLPzgbCCb0F1nnZ5aTcMCko_LmFqboWQLatiqCbfjQAMQQQtbY--dF3k2Cjn1sIby9TyI3WJq-XcMt83yfgMFsbHmGU5i6KYWP-qEruToR0rhPRfcyI-Gz8P_2oGnaof8iqj-v4FyMCP20tp3XUTDTXBB6zSxinGJpPFwQbamSNSgBQyBszGTykxZWYT6dIXG5t3bEgBrSlfQKT3q5J4dMeRS-rPqIA8kB6EmdkAMkdgKSypJXKvpy1deM6b8tU9t7zzWeu_rd4Ev3lMPUedvhi5dQa1yDNlvkec9v6d4Q--0ugXNSaOHVR_GJ2NADjNSwe2s6v0e9Qdl4rSJHoRwozY0we-_P1NYwAFkyS6hn48_1X_SUpxIpOVbLzcIspVZRR9MZAqvQA5nNA6r10YJqtYE_gzmzvcW3CO9D1b9u3LdzfQSOJy5vc5iJWaF48VVgybbjUbQHAb1ArVqaLkKqUuvzArA85blx2ti1FYpRRgj6mCjUgGW84S4q0W_dYFk27Sut3JyP8QEfddDOuBv91TqkPSl41e10vFpk5HEGWXzoIg7d_EkZiJzdEKRZk_teA0l677jtM-_ZPWOsnhrsfi-lKCaccA